create table public.line_user_state (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  source_id character varying null,
  source_type character varying null,
  function_name character varying null,
  constraint line_user_state_pkey primary key (id)
) TABLESPACE pg_default;